# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐞 Bug report
description: Please fill out all fields so we can triage your bug quickly.
labels: [Bug]

body:

  # 2) Description → required multiline textarea
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      placeholder: |
        Describe the bug in detail, including steps to reproduse it
    validations:
      required: true

  # 3) Location → dropdown with “Other” option
  - type: dropdown
    id: location
    attributes:
      label: 📍 Where is this happening?
      description: Select the component or area.
      options:
        - Home Page
        - Login Page
        - Register Page
        - Subjects Pages
        - Chapter Selection Pages
        - Other

  # 4) Custom location → always shown, fill only for “Other”
  - type: input
    id: custom_location
    attributes:
      label: ✏️ Custom location
      description: Fill this only if you selected “Other” above.
      placeholder: e.g. "Settings Page"

  # 5) Priority → single-choice dropdown
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Priority
      description: Wrong priority may result in ignored issues.
      options:
        - High
        - Medium
        - Low

  # 6) Screenshots/Logs → drag-and-drop in textarea
  - type: textarea
    id: attachments
    attributes:
      label: 📸 Screenshots or Logs
      placeholder: |
        Drag and drop any relevant images or log files here.