# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐞 Bug report
description: Please fill out all fields so we can triage your bug quickly.
labels: [Bug]

body:
  # 1) Title → required single-line input
  - type: input
    id: title
    attributes:
      label: ✍️ Title
      description: Give your bug a concise, descriptive title.
      placeholder: e.g. "App crashes on login"
    validations:
      required: true

  # 2) Description → required multiline textarea
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      placeholder: |
        Describe the bug in detail, including steps to reproduce
        and expected vs. actual behavior.
    validations:
      required: true

  # 3) Location → single-choice dropdown with “Other”
  - type: dropdown
    id: location
    attributes:
      label: 📍 Where is this happening?
      description: Select the component or area.
      options:
        - Home Page
        - Login Page
        - Register Page
        - Subjects Pages
        - Chapter Selection Pages
        - Slide panel
        - Profile page
        - Other
    validations:
      required: true

  # 4) Custom location → only shown if “Other” chosen
  - type: input
    if: ${{ inputs.location == 'Other' }}
    id: custom_location
    attributes:
      label: ✏️ Custom location
      description: Please specify your custom location here.
      placeholder: e.g. "Settings Page"

  # 5) Priority → single-choice dropdown
  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Priority
      description: Set a priority based on how much it bothers the user. Wrong priority may result in ignored issues.
      options:
        - High
        - Medium
        - Low

  # 6) Screenshots / Logs → textarea for drag-and-drop attachments
  - type: markdown
    attributes:
      value: |
        📸 **Attachments**  
        Once you submit this form, use the comment editor’s drag-and-drop or “attach files” button to upload screenshots or logs.  
        *(Maximum file size: 25 MB; image limit: 10 MB)* 