# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐞 Bug report
description: Please fill out this form so we can triage your issue as quickly as possible.
labels: [needs-triage]

body:
  - type: tags
    id: tags
    attributes:
      label: 📑 Tags
      description: Select or type tags (e.g., bug, enhancement, docs).
      # no options here means you can type any tag

  - type: input
    id: title
    attributes:
      label: ✍️ Short title
      description: Give your issue a concise title.
      placeholder: “E.g. App crashes on login”
      validations:
        required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Describe what happened, steps to reproduce, expected & actual behavior.
      validations:
        required: true

  - type: dropdown
    id: location
    attributes:
      label: 📍 Where is this happening?
      description: Choose the component or area.
      options:
        - Frontend
        - Backend
        - API
        - Database
        - Mobile
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Priority
      description: Wrong priority may result in ignored issues.
      options:
        - High
        - Medium
        - Low

  - type: attachments
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: Attach any relevant screenshots or logs.
