name: 🐞 Bug report
description: Please fill out all fields to help us investigate your issue.
labels: [needs-triage]

body:
  - type: tags
    id: tags
    attributes:
      label: 📑 Tags
      description: Select or type tags (e.g., bug, enhancement, docs).

  - type: input
    id: title
    attributes:
      label: ✍️ Short title
      description: A concise title for the issue.
      placeholder: “App crashes on login”
      validations:
        required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Steps to reproduce, expected vs. actual behavior.
      validations:
        required: true

  - type: dropdown
    id: location
    attributes:
      label: 📍 Where is this happening?
      description: Select the component or area.
      options:
        - Frontend
        - Backend
        - API
        - Database
        - Mobile
        - Other
      default: 0

  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Priority
      description: Wrong priority may result in ignored issues.
      options:
        - High
        - Medium
        - Low
      default: 1

  - type: attachments
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: Upload any relevant images or logs.
